#!/bin/bash
echo installation starts...
echo " "
lsb_release -a
user=$(whoami)
echo ""
file1="/usr/share/gpu-viewer"
file4="/usr/bin/vulkaninfo"
file5="/home/$user/Desktop/gpu-viewer.desktop"
file6="/usr/bin/gpu-viewer"
echo "************************GPU Viewer 1.21 - copyright(c) 2017-2020 - Arun Sivaraman****************************"
if [ ! -d "$file1" ]
then

	sudo mkdir /usr/share/gpu-viewer
fi
echo " "
echo "Installing Application files ...."
echo " "
sudo cp -vrf Files /usr/share/gpu-viewer
echo " "
echo "Application Files Successfully Installed...."
echo " "
echo "Installing Application Icons ...."
echo " "
sudo cp -vrf Images /usr/share/gpu-viewer
echo " "
echo "Application Icons Succesfully Installed ...."
echo ""
echo "Installing Supported Documents...."
echo " "
sudo cp -vrf About\ GPU\ Viewer /usr/share/gpu-viewer
sudo cp -vrf GPUViewer /usr/share/gpu-viewer
sudo cp -vrf Change\ Log /usr/share/gpu-viewer
sudo cp -vrf LICENSE /usr/share/gpu-viewer
sudo cp -vrf README.md /usr/share/gpu-viewer
sudo cp -vrf bin/vkcube /usr/bin
sudo cp -vrf bin/vulkaninfo /usr/bin
sudo cp -vrf bin/vkcubepp /usr/bin
echo " "
echo "Supporting documents Successfully Installed...."
echo " "
echo "Installing files completed..."
echo " "
sudo cp gpu-viewer.desktop /usr/share/applications/
echo " "
echo "Application successfully added to the menu"
if [ ! -f "$file6" ]
then
    sudo ln -s /usr/share/gpu-viewer/GPUViewer /usr/bin/gpu-viewer
    echo "Symlink created - Application can be accessed from Terminal, enter gpu-viewer ENTER "
fi
echo " "
if [ ! -f "$file5" ]
then
	read -p "Do you want to add a shortcut to desktop(y/n):" choice
    echo " "
	if [ $choice == 'y' ]
	then
    	sudo cp gpu-viewer.desktop /home/$user/Desktop/
	    sudo chown -R $user /home/$user/Desktop/gpu-viewer.desktop
    	echo "Desktop Shortcut successfully created ..."
        echo " "
	fi
fi
echo Installation complete...
echo "All done !!! Enjoy the Application"
echo "Consider supporting this application by giving a star on my Github repository (https://github.com/arunsivaramanneo/GPU-Viewer) or by donating (https://www.paypal.me/ArunSivaraman)"
date
